#!/bin/sh
# Stolen from https://medium.com/@mmessell/apply-spotless-formatting-with-git-pre-commit-hook-1c484ea68c34
stagedFiles=$(git diff --staged --name-only)
echo "Running spotlessApply. Formatting code..."
./gradlew spotlessApply
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done